public with sharing class classCollectionsExamples {
    public static void testList(){
        List<String> listNull;
        String[] anotherListNull;
        System.debug('El valor de la primera lista es : ' + listNull);
        System.debug('El valor de la segunda lista es : ' + anotherListNull);

        Account cuenta = new Account();


        System.debug('El valor de la primera');
        cuenta.NumberOfEmployees = 10;

        String hola = '';
    }
}